apiVersion: apps/v1
kind: Deployment
metadata:
  name: applink
  namespace: bns-1-dev
  labels:
    app: applink
spec:
  replicas: 1
  selector:
    matchLabels:
      app: applink
  template:
    metadata:
      labels:
        app: applink
    spec:
      containers:
      - name: tomcat
        image: tomcat:9.0-jre8-alpine
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: war-volume
          mountPath: /usr/local/tomcat/webapps/applink.war
          subPath: applink.war
      volumes:
      - name: war-volume
        configMap:
          name: applink-configmap
