apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: applink
  namespace: bns-1-dev
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: applink
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
